"""
Generate an EESchema schematic for a charlieplex

"""
import math
import sys
import os.path
import datetime, time
# calculate the offset taking into account daylight saving time
utc_offset_sec = time.altzone if time.localtime().tm_isdst else time.timezone
utc_offset = datetime.timedelta(seconds=-utc_offset_sec)
datestr=datetime.datetime.now().replace(tzinfo=datetime.timezone(offset=utc_offset)).isoformat()
def name_diode(i,slot_ofs=0,ring_ofs=0,mod=60,ringdigits=1,slotdigits=2):
    """
    Name a diode
    :param i: Zero-based diode number
    :param ofs: Set to 0 if D000 is allowed, set to 1 if you want to start at d
    :param mod:
    :return:
    """
    ring=i//mod+ring_ofs
    slot=i%mod+slot_ofs
    ringspace=10**slotdigits
    return ("D%%0%dd"%(ringdigits+slotdigits))%(ring*ringspace+slot)

def map_diode(i,wires):
    for ii_row in range(wires):
        n_diodes=(ii_row+1)*(ii_row+2)//2
        n_diodesm1=(ii_row)*(ii_row+1)//2
        if i<n_diodes:
            i_row=ii_row
            break
    i_col=i-n_diodesm1
    Npair=wires*(wires-1)//2
    cols_right=wires-i_col
    Nright=cols_right*(cols_right-1)//2
    Nleft=Npair-Nright
    print(i,i_row,i_col,wires-i_row+Nleft)
    return i_row-i_col+Nleft

def name_wire(i,ofs=1,digits=2):
    return ("Q%%0%dd"%(digits))%(i+ofs)

bidi=False
Npair=120 #Number of diodes (or pairs) to place
wires=math.ceil((math.sqrt(1+8*Npair)+1)/2)
for i_diode in range(Npair):
    map_diode(i_diode,wires)
with open("/home/jeppesen/workspace/eagle/KwanSystems/Precision/Precision Arduino Charlieplex 2.0/Charlieplex16.sch","w") as ouf:
    print("EESchema Schematic File Version 4",file=ouf)
    print("LIBS:Precision Arduino Charlieplex 2.0-cache",file=ouf)
    print("EELAYER 26 0",file=ouf)
    print("EELAYER END",file=ouf)
    print("$Descr A 11000 85000",file=ouf)
    print("encoding utf-8",file=ouf)
    print("Sheet 1 1",file=ouf)
    print('Title "Charlieplex with %d signals (%d pairs)"'%(wires,Npair),file=ouf)
    print('Date "%s"'%datestr,file=ouf)
    print('Rev ""',file=ouf)
    print('Comp ""',file=ouf)
    print('Comment1 "Generated by %s"'%os.path.basename(sys.argv[0]),file=ouf)
    print('Comment2 ""',file=ouf)
    print('Comment3 ""',file=ouf)
    print('Comment4 ""',file=ouf)
    print("$EndDescr",file=ouf)

    row0=  600
    row1=  100
    drow= -400
    row0=row0-wires*drow
    col0= 1000
    col1=  300
    dcol=  400

    i_pair=0
    for i_wire in range(wires):
        #Row wire
        if i_wire==wires-1:
            ofs=-200
        else:
            ofs=0
        print("Wire Wire Line",file=ouf)
        print("        %d %d %d %d"%(col0,row0+i_wire*drow,col0+col1+i_wire*dcol+ofs,row0+i_wire*drow),file=ouf)
        print("Text HLabel %d  %d  0    50 UnSpc ~ 0"%(col0,row0+i_wire*drow),file=ouf)
        print(name_wire(i_wire),file=ouf)
        if i_wire<wires-1:
            # Column wire
            print("Wire Wire Line",file=ouf)
            print("        %d %d %d %d" % (
            col0 + col1 + i_wire * dcol, row0 + i_wire * drow, col0 + col1 + i_wire * dcol, row0 + wires * drow+700),file=ouf)
            for i_rowpair in range(i_wire+1):
                xdevice=col0+col1+i_rowpair*dcol+200
                ydevice=row0+row1+i_wire*drow-350
                print("Wire Wire Line",file=ouf)
                print("        %d %d %d %d" %(xdevice-200,ydevice+150,xdevice,ydevice+150),file=ouf)
                print("Connection ~ %d %d "%(xdevice-200,ydevice+150),file=ouf)
                print("Connection ~ %d %d "%(xdevice    ,ydevice-150),file=ouf)
                # Connection ~ 900  600
                print("$Comp",file=ouf)
                print("L Device:LED %s"%name_diode(map_diode(i_pair,wires)),file=ouf)
                print("U 1 0 %016x"%(0xC247B3F4E982C629+i_pair),file=ouf)
                print("P %d %d"%(xdevice,ydevice),file=ouf)
                print('F 0 "%s" H %d %d 59  0000 L BNN'%(name_diode(map_diode(i_pair,wires)),xdevice-150,ydevice+50),file=ouf)
                print('F 1 "HOUR" V %d %d 59  0001 L BNN'%(xdevice,ydevice),file=ouf)
                print('F 2 "KwanSystems:LED-0603" H %d %d 50  0001 C CNN'%(xdevice,ydevice),file=ouf)
                print('F 3 "" H %d %d 50  0001 C CNN'%(xdevice,ydevice-50),file=ouf)
                print("     1    %d %d"%(xdevice,ydevice),file=ouf)
                print("     0   -1   1   0",file=ouf)
                print("$EndComp",file=ouf)
                i_pair+=1

    print("$EndSCHEMATC",file=ouf)